# Default values for micro-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

readinessProbe:
  path: /api/isalive

livenessProbe:
  path: /api/isalive

env: 
  "PSQL_DB_ADDRESS": "backend-postgresql"

image:
  repository: jantoth/microservice         
  tag: v0.0.1
  pullPolicy: IfNotPresent
  containerPort: 8000

nameOverride: ""
fullnameOverride: ""

service:
  # service types: ClusterIP, NodePort, LoadBalancer
  type: ClusterIP 
  port: 80
  targetPort: 8000
  nodePort: 30222

ingress:
  enabled: true
  annotations: 
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    
  paths: ["/api/.*"]
  hosts:
    - k8s.linuxinuse.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

postgresql:
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: latest
    debug: true

  postgresqlUsername: postgres
  
  postgresqlPassword: password
  
  persistence:
    enabled: false
    existingClaim: data-backend-postgresql-0
 
  pgHbaConfiguration: |
    local all all trust
    host all all localhost trust
    host microservice  micro 192.168.0.0/24 password

  initdbScripts:
    db-init.sql: |
      CREATE DATABASE  microservice;
      CREATE USER micro WITH ENCRYPTED PASSWORD 'password';
      GRANT ALL PRIVILEGES ON DATABASE microservice TO micro;
      ALTER DATABASE microservice OWNER TO micro;
