# Default values for micro-frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

readinessProbe:
  path: /app

livenessProbe:
  path: /app

image:
  repository: jantoth/frontend 
  tag: v0.0.3
  pullPolicy: IfNotPresent
  # This will be Nginx serving 
  # react app static content *.html, *.js, *.css
  containerPort: 80

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  # This will by default point out to 
  # `containerPort: 80` from section: image
  targetPort: 80
  nodePort: 30333

ingress:
  enabled: true
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: k8s.linuxinuse.com
      paths: ["/app/.*"]

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
